[theme]
# Primary accent color for interactive elements.
primaryColor = "#fcb54c"

# Background color for the main content area.
backgroundColor = "#371448"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#603575"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"